// CommonJS: builtins, fs round trips, timers, events, streams, exit code.
const fs = require('fs')
const path = require('node:path')
const os = require('os')
const util = require('util')
const { EventEmitter } = require('events')
const { Readable, pipeline } = require('stream')
const assert = require('assert')

const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'cjs-'))
const file = path.join(dir, 'a.txt')
fs.writeFileSync(file, 'héllo\n')
fs.appendFileSync(file, 'world\n')
assert.strictEqual(fs.readFileSync(file, 'utf8'), 'héllo\nworld\n')
assert.ok(Buffer.isBuffer(fs.readFileSync(file)))
const st = fs.statSync(file)
assert.ok(st.isFile() && !st.isDirectory() && st.size === 13 && st.mtime instanceof Date, util.inspect(st))
fs.mkdirSync(path.join(dir, 'x/y/z'), { recursive: true })
fs.symlinkSync(file, path.join(dir, 'x/link'))
assert.ok(fs.lstatSync(path.join(dir, 'x/link')).isSymbolicLink())
assert.strictEqual(fs.realpathSync(path.join(dir, 'x/link')), file)
const ents = fs.readdirSync(path.join(dir, 'x'), { withFileTypes: true })
assert.deepStrictEqual(ents.map((e) => [e.name, e.isDirectory(), e.isSymbolicLink()]).sort(), [['link', false, true], ['y', true, false]])
assert.deepStrictEqual(fs.readdirSync(dir, { recursive: true }).sort(), ['a.txt', 'x', 'x/link', 'x/y', 'x/y/z'])
const fd = fs.openSync(file, 'r+')
const buf = Buffer.alloc(5)
assert.strictEqual(fs.readSync(fd, buf, 0, 5, 7), 5)
assert.strictEqual(buf.toString(), 'world')
fs.writeSync(fd, 'W', 7)
fs.closeSync(fd)
assert.strictEqual(fs.readFileSync(file, 'latin1').slice(7, 12), 'World')
fs.renameSync(file, path.join(dir, 'b.txt'))
assert.ok(!fs.existsSync(file) && fs.existsSync(path.join(dir, 'b.txt')))
fs.cpSync(dir, dir + '-copy', { recursive: true })
assert.ok(fs.existsSync(dir + '-copy/x/y/z'))
assert.throws(() => fs.readFileSync('/nope/x'), (e) => e.code === 'ENOENT' && e.syscall === 'open' && e.errno === -2 && /no such file/.test(e.message))
fs.rmSync(dir, { recursive: true })
fs.rmSync(dir + '-copy', { recursive: true, force: true })
assert.ok(!fs.existsSync(dir))
// image files are readable and the image is read-only underneath an overlay
const pkg = JSON.parse(fs.readFileSync('/workspace/node_modules/react/package.json', 'utf8'))
assert.strictEqual(pkg.name, 'react')

const order = []
const ee = new EventEmitter()
ee.on('x', (v) => order.push('event ' + v))
setTimeout(() => order.push('timeout 5'), 5)
setTimeout(() => order.push('timeout 1'), 1)
setImmediate(() => order.push('immediate'))
process.nextTick(() => order.push('tick'))
Promise.resolve().then(() => order.push('microtask'))
ee.emit('x', 1)
const iv = setInterval(() => {}, 1000)
iv.unref()
const t = setTimeout(() => order.push('never'), 50)
clearTimeout(t)

let streamed = ''
pipeline(Readable.from(['a', 'b', 'c']), async function* (src) { for await (const c of src) yield c.toUpperCase() }, async (src) => { for await (const c of src) streamed += c }, (err) => {
  assert.ifError(err)
  order.push('pipeline ' + streamed)
})

fs.promises.readFile('/workspace/package.json', 'utf8').then((text) => order.push('promise ' + JSON.parse(text).name))
fs.readFile('/workspace/package.json', (err, data) => { assert.ifError(err); order.push('callback ' + data.length) })

process.on('beforeExit', () => {
  if (order.includes('beforeExit')) return
  order.push('beforeExit')
  setTimeout(() => order.push('after beforeExit'), 1)
})
process.on('exit', (code) => {
  console.log(order.join('\n'))
  console.log(util.format('%s %d %j %o', 'fmt', 42, { a: 1 }, [1, 'two']))
  console.log(util.inspect({ a: 1, b: 'x', c: [1, 2, { d: new Map([[1, 2]]) }], e: Buffer.from('hi') }))
  console.log('platform', process.platform, os.platform(), os.tmpdir(), os.EOL === '\n', path.resolve('a/../b'), typeof self, typeof window, typeof importScripts, typeof postMessage, typeof global, typeof require, typeof __dirname)
  console.log('exit code', code)
})
process.exitCode = 7
